services:
  web:
    image: nginx-web:latest
    restart: unless-stopped
    env_file:
      - .env

    read_only: true
    tmpfs:
      - /tmp:uid=101,gid=101,mode=1777
      - /var/cache/nginx:uid=101,gid=101,mode=0755
      - /etc/nginx/conf.d:uid=101,gid=101,mode=0755
      - /var/log/nginx:uid=101,gid=101,mode=0755

    volumes:
      - html:/usr/share/nginx/html:ro
      # Certificates
      # This is a read-only volume, so the container cannot modify the certificates
      # Enable this if you want to use HTTPS
      # - ./certs:/etc/ssl/certs:ro

    networks:
      internal: {}

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    healthcheck:
      test: >
        CMD-SHELL
        (curl -fs http://localhost/ || curl -kfs https://localhost/) || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
